[Settings]
# 开启酒店源功能，关闭后所有酒店源工作模式都将关闭; 可选值: True, False | Enable hotel source function, after closing, all hotel source working modes will be closed; Optional values: True, False
open_hotel = False
# 生成结果文件路径; 默认值: output/result.txt | Generate result file path; Default value: output/result.txt
final_file = output/user_result.txt
# 强制认为当前网络支持IPv6，跳过检测 | Force to consider that the current network supports IPv6, skip detection
ipv6_support = True
# 模板文件路径， 默认值: config/demo.txt | Template file path, Default value: config/demo.txt
source_file = config/user_demo.txt
# 单个频道接口数量 | Number of interfaces per channel
urls_limit = 10
# 开启组播源功能，关闭后所有组播源工作模式都将关闭; 可选值: True, False | Enable multicast source function, after closing, all multicast source working modes will be closed; Optional values: True, False
open_multicast = False
# 开启 Foodie 组播源工作模式; 可选值: True, False | Enable Foodie multicast source working mode; Optional values: True, False
open_multicast_foodie = False
# 更新时间显示位置，需要开启 open_update_time 才能生效，可选值：top、bottom，top: 显示于结果顶部，bottom: 显示于结果底部 | Update time display position, need to enable open_update_time to take effect, optional values: top, bottom, top: display at the top of the result, bottom: display at the bottom of the result
update_time_position = bottom
# 开启分辨率过滤，低于最小分辨率（min_resolution）的接口将会被过滤，GUI用户需要手动安装FFmpeg，程序会自动调用FFmpeg获取接口分辨率，推荐开启，虽然会增加测速阶段耗时，但能更有效地区分是否可播放的接口，可选值：True, False | Enable resolution filtering, interfaces below the minimum resolution (min_resolution) will be filtered, GUI users need to manually install FFmpeg, the program will automatically call FFmpeg to obtain the interface resolution, it is recommended to enable, although it will increase the time-consuming of the speed measurement stage, but it can more effectively distinguish whether the interface can be played, optional values: True, False
open_filter_resolution = False
# 开启速率过滤，低于最小速率（min_speed）的接口将会被过滤; 可选值: True, False | Enable rate filtering, interfaces below the minimum rate (min_speed) will be filtered; Optional values: True, False
open_filter_speed = False
# 开启排序功能（响应速度、日期、分辨率）; 可选值: True, False | Enable sorting function (response speed, date, resolution); Optional values: True, False
open_sort = False
# 开启补偿机制模式，用于控制当频道接口数量不足时，自动将不满足条件（例如低于最小速率）但可能可用的接口添加至结果中，从而避免结果为空的情况; 可选值: True, False | Enable compensation mechanism mode, used to control when the number of channel interfaces is insufficient, automatically add interfaces that do not meet the conditions (such as lower than the minimum rate) but may be available to the result, thereby avoiding the result being empty; Optional values: True, False
open_supply = False
# 开启使用本地缓存数据，适用于查询请求失败场景（仅针对酒店源与组播源）; 可选值: True, False | Enable to use local cached data, suitable for query request failure scenarios (only for hotel source and multicast source); Optional values: True, False
open_use_cache = False
# 开启使用历史更新结果（包含模板与结果文件的接口），合并至本次更新中; 可选值: True, False | Enable to use historical update results (including interfaces of templates and result files), merged into this update; Optional values: True, False
open_history = False
