[Settings]
# 开启EPG功能，支持频道显示预告内容；可选值: True, False | Enable EPG function, support channel display preview content; Optional values: True, False
open_epg = True
# 生成结果文件路径; 默认值: output/result.txt | Generate result file path; Default value: output/result.txt
final_file = output/user_result.txt
# 结果中偏好的 IPv4 接口数量 | Preferred number of IPv4 interfaces in the result
ipv4_num = 10
# 结果中偏好的 IPv6 接口数量 | Preferred number of IPv6 interfaces in the result
ipv6_num = 10
# 模板文件路径， 默认值: config/demo.txt | Template file path, Default value: config/demo.txt
source_file = config/user_demo.txt
