[Settings]
# 开启酒店源功能，关闭后所有酒店源工作模式都将关闭; 可选值: True, False | Enable hotel source function, after closing, all hotel source working modes will be closed; Optional values: True, False
open_hotel = False
# 生成结果文件路径; 默认值: output/result.txt | Generate result file path; Default value: output/result.txt
final_file = output/user_result.txt
# 结果中偏好的 IPv4 接口数量 | Preferred number of IPv4 interfaces in the result
ipv4_num = 5
# 结果中偏好的 IPv6 接口数量 | Preferred number of IPv6 interfaces in the result
ipv6_num = 5
# 强制认为当前网络支持IPv6，跳过检测 | Force to consider that the current network supports IPv6, skip detection
ipv6_support = True
# 模板文件路径， 默认值: config/demo.txt | Template file path, Default value: config/demo.txt
source_file = config/user_demo.txt
# 单个频道接口数量 | Number of interfaces per channel
urls_limit = 1
